CREATE TABLE BOOK (
	id varchar(100) NOT NULL,
	name varchar(100) NULL,
	author varchar(100) NULL,
	create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	create_by varchar(100) DEFAULT "SYSTEM" NOT NULL,
	update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	update_by varchar(100) DEFAULT "SYSTEM" NOT NULL,
	CONSTRAINT BOOK_PK PRIMARY KEY (id)
);